version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  go: "1.23"

linters:
  default: standard
  enable:
    - govet
    - staticcheck
    - revive
    - ineffassign
    - errcheck
formatters:
  enable:
    - gofmt

output:
  formats:
    text:
      path: stdout
      colors: true
