# .github/workflows/ci.yml
name: Go CI

on:
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: "1.23.x", cache: true }
      - run: go mod download
      - run: go build ./...
      - run: go test ./... -v -race -coverprofile=coverage.out
      - uses: actions/upload-artifact@v4
        with: { name: coverage-report, path: coverage.out }

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: "1.23.x", cache: true }
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.0
          args: --timeout=5m
